# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('FQLearn_rcpparma_hello_world', PACKAGE = 'FQLearn')
}

rcpparma_outerproduct <- function(x) {
    .Call('FQLearn_rcpparma_outerproduct', PACKAGE = 'FQLearn', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('FQLearn_rcpparma_innerproduct', PACKAGE = 'FQLearn', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('FQLearn_rcpparma_bothproducts', PACKAGE = 'FQLearn', x)
}

newProjectionNoStage <- function(input, p, L) {
    .Call('FQLearn_newProjectionNoStage', PACKAGE = 'FQLearn', input, p, L)
}

newLikelihoodNoStage <- function(input, indices, rho, p, L, m, B_T0, data, indexVec) {
    .Call('FQLearn_newLikelihoodNoStage', PACKAGE = 'FQLearn', input, indices, rho, p, L, m, B_T0, data, indexVec)
}

newGradientNoStage <- function(input, indices, rho, p, L, m, B_T0, data, indexVec) {
    .Call('FQLearn_newGradientNoStage', PACKAGE = 'FQLearn', input, indices, rho, p, L, m, B_T0, data, indexVec)
}

newDescentFullOnlyNoStage <- function(fulldata, Obasis, input, rho, p, iter2, stepsizes, tol) {
    .Call('FQLearn_newDescentFullOnlyNoStage', PACKAGE = 'FQLearn', fulldata, Obasis, input, rho, p, iter2, stepsizes, tol)
}

